doctors/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

doctors/doctors/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from posts import views as posts_views

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include("accounts.urls")),
    url(r'^posts/', include("posts.urls")),
    url(r'^$',views.homepage,name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

doctors/posts/urls.py
from django.conf.urls import url
from .import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.newsfeed, name="newsfeed"),
    url(r'^create/$', views.post_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail")
]

doctors/accounts/models.py
from django.db import models

# Create your models here.

doctors/posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Posts(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumbnail = models.ImageField(default="default.jpg", blank=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE ,default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:20] + "..."

doctors/posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Posts
        fields = {'title','body','slug','thumbnail'}

doctors/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('posts:newsfeed')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

doctors/doctors/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, "homepage.html")

doctors/posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Posts
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.

def newsfeed(request):
    posts = Posts.objects.all().order_by("date")
    return render(request,"posts/newsfeed.html", {'posts':posts})

def post_detail(request,slug):
    #return HttpResponse(slug)
    post = Posts.objects.get(slug=slug)
    return render(request, 'posts/post_detail.html',{'post': post})

@login_required(login_url='/accounts/login/')
def post_create(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST,request.FILES)
        if form.is_valid():
            value = form.save(commit=False)
            value.author = request.user
            value.save()
            return redirect('posts:newsfeed')
    else:   
        form = forms.CreatePost()
    return render(request,'posts/post_create.html', {'form':form})

doctors/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Log in</h1>
<div class="center-form">
    <form action="{% url 'accounts:login' %}" class="site-form" method="POST">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="login">
    </form>
</div>
{% endblock %}

doctors/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign Up</h1>
<div class="center-form">
    <form class="site-form" action="/accounts/signup/" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="SignUp">
    </form>
</div>
{% endblock %}

doctors/posts/templates/posts/newsfeed.html
{% extends 'base.html' %}

{% block content %}
    <h1>POSTS</h1>
    <div class="posts">
        {% for post in posts %}
            <div class="post">
                <h2><a href="{% url 'posts:detail' slug=post.slug %}"> {{post.title}} </a></h2>
                <p> {{post.snippet}} </p>
                <p> {{post.date}} </p>
                <p class="author">Posted by {{ post.author.username }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

doctors/posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="post-create">
        <form action="{% url 'posts:create' %}" class="site-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

doctors/posts/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="post-detail">
    <div class="post">
        <img src="{{ post.thumbnail.url }}"/>
        <h2>{{post.title}}</h2>
        <p>{{post.body}}</p>
        <p>{{post.date}}</p>
    </div>
</div>
{% endblock %}

doctors/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Newsfeed</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header class="wrapper">
        <h1 class="logo"><a href="{% url 'home' %}">Steth-Talk</a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn" type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'posts:create' %}" class="btn" >New Post</a></li>
                {% else %}
                <li class="btn"><a href="{% url 'accounts:login' %}">Login</a></li>
                <li class="btn"><a href="{% url 'accounts:signup' %}">SignUp</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

doctors/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomePage</title>
    <link rel="stylesheet" href="{% static 'homepage.css' %}">
</head>
<body>
    <header class="wrapper">
        <h1 class="logo"><a href="{% url 'home' %}">Steth-Talk</a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="btn" type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'posts:create' %}" class="highlight" >New Post</a></li>
                {% else %}
                <li class="btn"><a href="{% url 'accounts:login' %}">Login</a></li>
                <li class="btn"><a href="{% url 'accounts:signup' %}">SignUp</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="intro">
        <p class="p-intro">Where Doctors can write posts</p>
        <li class="tour-btn"><a href="{% url 'posts:newsfeed' %}">Take a tour</a></li>
    </div>
</body>
</html>